import { Accessibility, Building2, CheckCircle2, ChevronRight, Filter, HeartPulse, Map as MapIcon, Search, UsersRound } from 'lucide-react';
import { AppShell, PageTitle, SectionHeading } from '@/components/shell';
import { MapPanel } from '@/components/map-panel';
import { Button, Donut, FilterButton, StatusBadge } from '@/components/ui';

const facilities = [
  ['Gauhati Medical College', 'Guwahati · Assam', '98', 'Hospital', 'good'],
  ['Civil Hospital Shillong', 'Shillong · Meghalaya', '92', 'Hospital', 'good'],
  ['JNIMS Relief Centre', 'Imphal · Manipur', '84', 'Relief centre', 'watch'],
  ['Aizawl District Hub', 'Aizawl · Mizoram', '76', 'Logistics hub', 'watch'],
  ['Agartala Transit Point', 'Agartala · Tripura', '71', 'Transit point', 'critical'],
];

export default function AccessibilityPage() {
  return <AppShell><PageTitle kicker="ACCESSIBILITY INTELLIGENCE" title="The last mile matters." description="A facility-level view of who can arrive, rest, reload and recover along the network." actions={<Button kind="secondary" icon={Filter} onClick={() => undefined} data-testid="button-accessibility-filters">Filter view</Button>} />
    <div className="access-summary-grid"><section className="panel access-overview"><SectionHeading title="Regional access score" meta="156 facilities assessed" /><div className="access-overview-body"><Donut value="89.2" label="out of 100" tone="amber" /><div className="access-summary-copy"><strong>Strong coverage, uneven edges.</strong><p>Core city hubs are ready. Remote facilities across Mizoram and Manipur need a closer look before the next dispatch cycle.</p><div className="access-mini-stats"><span><b>112</b><small>Fully accessible</small></span><span><b>31</b><small>Partial access</small></span><span><b>13</b><small>Needs review</small></span></div></div></div></section><section className="panel access-breakdown"><SectionHeading title="Score dimensions" meta="Regional average" /><div className="dimension-row"><span><Accessibility size={15} /> Physical entry</span><b>92</b><div className="dimension-bar"><i style={{ width: '92%' }} /></div></div><div className="dimension-row"><span><UsersRound size={15} /> Support capacity</span><b>87</b><div className="dimension-bar"><i style={{ width: '87%' }} /></div></div><div className="dimension-row"><span><HeartPulse size={15} /> Medical readiness</span><b>89</b><div className="dimension-bar"><i style={{ width: '89%' }} /></div></div><div className="dimension-row"><span><Building2 size={15} /> Transport access</span><b>86</b><div className="dimension-bar"><i style={{ width: '86%' }} /></div></div></section></div>
    <div className="access-content"><section className="panel facility-panel"><div className="facility-head"><SectionHeading title="Facilities" meta="Showing 5 of 156" /><div className="view-toggle"><button className="is-selected" onClick={() => undefined} data-testid="button-facilities-list"><Search size={14} /> List</button><button onClick={() => undefined} data-testid="button-facilities-map"><MapIcon size={14} /> Map</button></div></div><label className="inline-search"><Search size={15} /><input placeholder="Find facility, city or state" data-testid="input-facility-search" /></label><div className="facility-list">{facilities.map(([name, location, score, type, tone], index) => <button className="facility-row" key={name} onClick={() => undefined} data-testid={`button-facility-${index}`}><span className={`facility-score score-${tone}`}>{score}</span><span className="facility-info"><strong>{name}</strong><small>{location} <i>·</i> {type}</small></span><span className="facility-status"><StatusBadge tone={tone as 'good' | 'watch' | 'critical'}>{tone === 'good' ? 'Ready' : tone === 'watch' ? 'Partial' : 'Review'}</StatusBadge><ChevronRight size={15} /></span></button>)}</div><button className="load-more" onClick={() => undefined} data-testid="button-load-more-facilities">Load all facilities <ChevronRight size={14} /></button></section><section className="panel access-map-panel"><MapPanel title="Access coverage" subtitle="156 FACILITIES · 08 STATES" points={[{ x: 43, y: 31, tone: 'teal' }, { x: 53, y: 40, tone: 'teal' }, { x: 64, y: 48, tone: 'amber' }, { x: 74, y: 62, tone: 'red' }, { x: 37, y: 63, tone: 'amber' }, { x: 48, y: 72, tone: 'teal' }]} /></section></div>
    <div className="access-note"><CheckCircle2 size={18} /><p><b>Coverage note:</b> Scores combine physical access, accessible transport, trained support staff and medical response time. Last field verification: 14 June 2024.</p><button className="text-action" onClick={() => undefined} data-testid="button-view-methodology">View methodology <ChevronRight size={14} /></button></div>
  </AppShell>;
}