import { BarChart3, Edit3, MoreHorizontal, Plus, Search, Settings2, Trash2, TrendingUp, UsersRound } from 'lucide-react';
import { AppShell, PageTitle, SectionHeading } from '@/components/shell';
import { Button, StatusBadge } from '@/components/ui';

const routes = [['NH-37', 'Jorhat → Imphal', '438 km', '94.8%', 'Active'], ['NH-6', 'Shillong → Silchar', '310 km', '89.2%', 'Active'], ['NH-10', 'Siliguri → Gangtok', '114 km', '68.4%', 'Watch'], ['NH-15', 'Tinsukia → Pasighat', '208 km', '86.1%', 'Active']];
const incidents = [['INC-240617', 'Landslide watch', 'NH-10 · Sikkim', 'High', 'Open'], ['INC-240616', 'Roadway restriction', 'SH-9 · Mizoram', 'Medium', 'Monitoring'], ['INC-240615', 'Flooding cleared', 'NH-37 · Assam', 'Resolved', 'Closed']];
const hubs = [['Guwahati Central', 'Assam', 'Primary', '42 / 48', 'Operational'], ['Dimapur Interchange', 'Nagaland', 'Transit', '19 / 24', 'Operational'], ['Aizawl District Hub', 'Mizoram', 'Relief', '11 / 16', 'Review']];

export default function Admin() {
  const action = (label: string) => <button className="table-icon-button" aria-label={label} onClick={() => undefined} data-testid={`button-${label.toLowerCase().replaceAll(' ', '-')}`}><Edit3 size={14} /></button>;
  return <AppShell><PageTitle kicker="ADMINISTRATION / CONTROL PLANE" title="Keep the system ready." description="Manage the network definitions and people behind the regional operating picture." actions={<Button icon={Settings2} onClick={() => undefined} data-testid="button-admin-settings">System settings</Button>} />
    <div className="admin-tabs"><button className="is-active" onClick={() => undefined} data-testid="button-admin-routes">Routes <span>24</span></button><button onClick={() => undefined} data-testid="button-admin-incidents">Incidents <span>12</span></button><button onClick={() => undefined} data-testid="button-admin-hubs">Logistics hubs <span>18</span></button><button onClick={() => undefined} data-testid="button-admin-users">Users <span>36</span></button></div>
    <section className="panel admin-section"><div className="admin-section-head"><SectionHeading title="Routes" meta="24 defined corridors" /><div className="admin-actions"><label className="mini-search"><Search size={14} /><input placeholder="Search routes" data-testid="input-search-routes" /></label><button className="button button-primary" onClick={() => undefined} data-testid="button-add-route"><Plus size={15} /> Add route</button></div></div><div className="admin-table"><div className="admin-thead"><span>Route</span><span>Corridor</span><span>Length</span><span>Readiness</span><span>Status</span><span>Actions</span></div>{routes.map(([code, corridor, length, readiness, status], index) => <div className="admin-tr" key={code}><b className="route-code">{code}</b><span>{corridor}</span><span className="mono-text">{length}</span><span className="readiness-cell"><i style={{ width: readiness }} />{readiness}</span><StatusBadge tone={status === 'Watch' ? 'watch' : 'good'}>{status}</StatusBadge><span className="row-actions">{action(`Edit ${code}`)}<button className="table-icon-button danger-icon" aria-label={`Delete ${code}`} onClick={() => undefined} data-testid={`button-delete-route-${index}`}><Trash2 size={14} /></button></span></div>)}</div></section>
    <div className="admin-grid"><section className="panel admin-small"><SectionHeading title="Incidents" meta="Recent activity" action={<button className="panel-more" onClick={() => undefined} data-testid="button-incidents-more"><MoreHorizontal size={17} /></button>} />{incidents.map(([id, name, location, severity, status]) => <div className="incident-item" key={id}><span className={`incident-mark mark-${severity.toLowerCase()}`} /><div><b>{name}</b><small>{location} · {id}</small></div><StatusBadge tone={severity === 'High' ? 'critical' : severity === 'Medium' ? 'watch' : 'good'}>{status}</StatusBadge></div>)}<button className="load-more" onClick={() => undefined} data-testid="button-view-incidents">View all incidents <TrendingUp size={14} /></button></section><section className="panel admin-small"><SectionHeading title="Logistics hubs" meta="18 registered" action={<button className="panel-more" onClick={() => undefined} data-testid="button-hubs-more"><MoreHorizontal size={17} /></button>} />{hubs.map(([name, state, type, capacity, status]) => <div className="hub-item" key={name}><span className="hub-icon"><BarChart3 size={15} /></span><div><b>{name}</b><small>{state} · {type}</small></div><div className="hub-capacity"><b>{capacity}</b><small>capacity</small></div><StatusBadge tone={status === 'Review' ? 'watch' : 'good'}>{status}</StatusBadge></div>)}<button className="load-more" onClick={() => undefined} data-testid="button-view-hubs">Manage hubs <Plus size={14} /></button></section></div>
    <div className="admin-bottom"><section className="panel chart-panel"><SectionHeading title="Network activity" meta="Dispatches · last 7 days" /><div className="fake-chart"><div className="chart-y"><span>80</span><span>60</span><span>40</span><span>20</span><span>0</span></div><div className="chart-area"><div className="chart-lines" /><svg viewBox="0 0 600 170" preserveAspectRatio="none" aria-label="Network activity chart"><path d="M0,130 C45,125 45,102 90,108 S135,84 175,95 S225,70 260,79 S310,55 345,70 S392,36 430,57 S475,67 510,38 S560,50 600,19" /><path className="chart-fill" d="M0,130 C45,125 45,102 90,108 S135,84 175,95 S225,70 260,79 S310,55 345,70 S392,36 430,57 S475,67 510,38 S560,50 600,19 L600,170 L0,170 Z" /></svg><div className="chart-x"><span>11 JUN</span><span>12 JUN</span><span>13 JUN</span><span>14 JUN</span><span>15 JUN</span><span>16 JUN</span><span>17 JUN</span></div></div></div></section><section className="panel chart-panel"><SectionHeading title="Team distribution" meta="By role" /><div className="team-chart"><div className="team-donut"><strong>36</strong><span>users</span></div><div className="team-legend"><span><i className="legend-square square-amber" /> Coordinators <b>14</b></span><span><i className="legend-square square-teal" /> Field teams <b>12</b></span><span><i className="legend-square square-navy" /> Planners <b>06</b></span><span><i className="legend-square square-sand" /> Viewers <b>04</b></span></div></div><button className="load-more" onClick={() => undefined} data-testid="button-manage-users"><UsersRound size={14} /> Manage users</button></section></div>
  </AppShell>;
}