import { ArrowUpRight, ChevronDown, Download, Filter, Flame, MoreHorizontal, RadioTower, ShieldAlert } from 'lucide-react';
import { AppShell, PageTitle, SectionHeading } from '@/components/shell';
import { MapPanel } from '@/components/map-panel';
import { Button, FilterButton, StatusBadge } from '@/components/ui';

const risks = [
  ['Landslide watch', 'NH-10 · Rangpo–Gangtok', 'Sikkim', 'High', '02h ago', 'critical', '12 km affected'],
  ['Heavy rainfall', 'NH-37 · Jorhat–Imphal', 'Assam', 'Medium', '04h ago', 'watch', 'Forecast · 82mm'],
  ['Roadway restriction', 'SH-9 · Aizawl bypass', 'Mizoram', 'Medium', '06h ago', 'watch', 'One lane open'],
  ['Low visibility', 'NH-6 · Shillong–Silchar', 'Meghalaya', 'Low', '07h ago', 'info', '1.8 km visibility'],
  ['River level rising', 'Dibang corridor · Roing', 'Arunachal Pradesh', 'High', '09h ago', 'critical', '+1.2m / 6 hours'],
];

export default function Risks() {
  return <AppShell><PageTitle kicker="RISK & ALERT SYSTEM" title="Watch the edges." description="The conditions that can turn a ready route into a decision." actions={<><Button kind="secondary" icon={Download} onClick={() => undefined} data-testid="button-export-risks">Export log</Button><Button icon={RadioTower} onClick={() => undefined} data-testid="button-alert-settings">Alert settings</Button></>} />
    <div className="risk-summary"><div className="risk-total"><span className="risk-total-icon"><ShieldAlert size={20} /></span><div><b>12</b><span>active risks across the region</span></div></div><div className="risk-summary-item"><span className="risk-dot dot-critical" /><b>04</b><span>High severity</span></div><div className="risk-summary-item"><span className="risk-dot dot-watch" /><b>06</b><span>Under watch</span></div><div className="risk-summary-item"><span className="risk-dot dot-info" /><b>02</b><span>Informational</span></div><div className="risk-summary-updated">LAST TRIAGED<br /><b>08:39 IST</b></div></div>
    <div className="risk-layout"><section className="panel risk-table-panel"><div className="risk-table-head"><SectionHeading title="Active risk register" meta="12 open items · sorted by severity" /><div className="risk-controls"><FilterButton /><button className="sort-button" onClick={() => undefined} data-testid="button-sort-risks">Severity <ChevronDown size={14} /></button></div></div><div className="risk-table"><div className="risk-thead"><span>Condition</span><span>Corridor / location</span><span>Severity</span><span>Updated</span><span>Impact</span><span /></div>{risks.map(([condition, corridor, state, severity, updated, tone, impact], index) => <div className="risk-tr" key={condition}><span className="risk-condition"><i className={`risk-icon risk-icon-${tone}`} /> <b>{condition}</b></span><span><strong>{corridor}</strong><small>{state}</small></span><StatusBadge tone={tone as 'critical' | 'watch' | 'info'}>{severity}</StatusBadge><span className="mono-text">{updated}</span><span>{impact}</span><button className="row-more" onClick={() => undefined} aria-label={`More actions for ${condition}`} data-testid={`button-risk-more-${index}`}><MoreHorizontal size={16} /></button></div>)}</div><div className="table-footer"><span>Showing 5 of 12 active risks</span><button className="table-link" onClick={() => undefined} data-testid="button-view-risk-history">View resolved history <ArrowUpRight size={13} /></button></div></section><section className="panel risk-map-panel"><MapPanel title="Risk concentration" subtitle="12 ACTIVE RISK POINTS" points={[{ x: 48, y: 26, tone: 'red', label: '03' }, { x: 35, y: 43, tone: 'amber', label: '02' }, { x: 55, y: 52, tone: 'red', label: '04' }, { x: 72, y: 64, tone: 'amber', label: '02' }, { x: 41, y: 67, tone: 'amber' }]} /><div className="risk-map-foot"><span><i className="legend-dot legend-red" /> High severity</span><span><i className="legend-dot legend-amber" /> Under watch</span><button className="text-action" onClick={() => undefined} data-testid="button-open-full-risk-map">Open full map <ArrowUpRight size={13} /></button></div></section></div>
    <section className="risk-insight"><span><Flame size={18} /></span><div><div className="eyebrow">SYSTEM SIGNAL</div><p>Risk density is highest across the <b>eastern Meghalaya–Manipur arc</b>. Three active corridors share the same rainfall cell. Consider grouping the next dispatch review around this cluster.</p></div><button className="button button-secondary" onClick={() => undefined} data-testid="button-create-review">Create review <ArrowUpRight size={14} /></button></section>
  </AppShell>;
}