import { ArrowDown, ArrowRight, BrainCircuit, CheckCircle2, Clock3, CloudRain, Fuel, LocateFixed, Map as MapIcon, Route as RouteIcon, ShieldAlert, SlidersHorizontal, Truck, Zap } from 'lucide-react';
import { AppShell, PageTitle, SectionHeading } from '@/components/shell';
import { MapPanel } from '@/components/map-panel';
import { Button, StatusBadge } from '@/components/ui';

export default function Routes() {
  return <AppShell><PageTitle kicker="ROUTE INTELLIGENCE / PLANNER" title="Find the way through." description="Compare route readiness across terrain, weather and access — before dispatch." actions={<Button kind="secondary" icon={SlidersHorizontal} onClick={() => undefined} data-testid="button-route-preferences">Preferences</Button>} />
    <section className="route-search panel"><div className="route-search-field"><label>ORIGIN</label><div><LocateFixed size={16} /><span>Guwahati, Assam</span></div></div><ArrowRight className="route-search-arrow" size={18} /><div className="route-search-field"><label>DESTINATION</label><div><MapIcon size={16} /><span>Imphal, Manipur</span></div></div><div className="route-search-field route-search-meta"><label>DEPARTURE</label><div><Clock3 size={15} /><span>Now · 08:45 IST</span></div></div><Button icon={RouteIcon} onClick={() => undefined} data-testid="button-plan-route">Plan route</Button></section>
    <div className="route-layout"><div className="route-results">
      <div className="route-results-head"><div><div className="eyebrow">RECOMMENDED ROUTE</div><h2>NH-37 via Dimapur</h2><span>Primary corridor · 438 km</span></div><StatusBadge tone="good">READY TO DISPATCH</StatusBadge></div>
      <div className="route-kpis"><div><Clock3 size={16} /><span>ETA</span><b>10h 35m</b></div><div><Truck size={16} /><span>ROAD QUALITY</span><b>Good</b></div><div><Fuel size={16} /><span>FUEL STOPS</span><b>04 planned</b></div></div>
      <div className="route-timeline"><div className="timeline-line" /><div className="route-stop"><span className="stop-dot stop-start" /><div><b>Guwahati logistics hub</b><small>Depart · 08:45 IST</small></div><StatusBadge tone="good">Open</StatusBadge></div><div className="route-stop"><span className="stop-dot stop-mid" /><div><b>Dimapur freight interchange</b><small>Checkpoint · 14:10 IST</small></div><StatusBadge tone="good">Open</StatusBadge></div><div className="route-stop"><span className="stop-dot stop-end" /><div><b>Imphal city distribution</b><small>Arrival · 19:20 IST</small></div><StatusBadge tone="info">Planned</StatusBadge></div></div>
      <div className="route-access"><div className="access-score"><div className="score-ring"><strong>88</strong><small>/ 100</small></div><div><b>Access confidence</b><span>Suitable for standard and accessible freight</span></div></div><div className="access-flags"><span><CheckCircle2 size={15} /> 6 accessible stops</span><span><ShieldAlert size={15} /> 1 monitored pass</span></div></div>
      <div className="alternate-route"><div><div className="eyebrow">ALTERNATE ROUTE</div><h3>NH-6 via Shillong</h3><span>+ 74 km · + 2h 20m</span></div><div className="alt-reason"><CloudRain size={16} /><span>Lower exposure to current rainfall cell</span></div><button className="button button-secondary" onClick={() => undefined} data-testid="button-compare-alternate">Compare <ArrowRight size={15} /></button></div>
    </div><div className="route-map-column"><MapPanel title="Guwahati → Imphal" subtitle="ROUTE COMPARISON · 2 OPTIONS" points={[{ x: 30, y: 31, tone: 'teal', label: 'A' }, { x: 54, y: 52, tone: 'amber' }, { x: 74, y: 64, tone: 'teal', label: 'B' }]} /><div className="route-legend"><span><i className="legend-line line-primary" /> Recommended</span><span><i className="legend-line line-alternate" /> Alternate</span><span><i className="legend-dot legend-red" /> Watch point</span></div></div></div>
    <section className="panel reasoning-panel"><div className="reasoning-icon"><BrainCircuit size={19} /></div><div><div className="eyebrow">AI ROUTE REASONING</div><h3>Why this route, right now?</h3><p>NH-37 is <b>12 minutes faster</b> than its 7-day average and has three confirmed fuel points with accessible washrooms. A rainfall cell is tracking east of Jiribam, but current visibility remains clear through the planned arrival window.</p><div className="reasoning-tags"><span><Zap size={13} /> Faster than baseline</span><span><Fuel size={13} /> Fuel assured</span><span><CheckCircle2 size={13} /> Access verified</span></div></div><button className="text-action" onClick={() => undefined} data-testid="button-expand-reasoning">Full reasoning <ArrowDown size={14} /></button></section>
  </AppShell>;
}